### ISSUE TITLE
Error: failed to get contents 

### ISSUE THREAD

**Issue by loboc101** [gbrueckl/Azure.DataFactory.PowerBIMonitor#2]
I am getting following error when trying to get data in this file: 
![Capture](https://user-images.githubusercontent.com/49783638/85121654-c7ecec00-b242-11ea-818b-11c2ea67d2a1.JPG)

**Comment by gbrueckl** [comment]
hi, this PowerBI workbook is for Azure Datafactory V1 only and does not support V2 - I guess this is your issue here.
There are currently no plans to support V2 as it fundamentally different
